[platformio]
src_dir = satellite-firmware/src
include_dir = satellite-firmware/include

[env:mkrwan1310]
platform = atmelsam
board = mkrwan1310
framework = arduino
monitor_speed = 115200

lib_deps =
    arduino-libraries/RTCZero
    arduino-libraries/Arduino_BQ24195
    arduino-libraries/Arduino_MKRGPS
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    sandeepmistry/LoRa
