[platformio]
default_envs = mkrwifi1010
src_dir = .

[env]
framework = arduino
monitor_speed = 115200

[env:mkrwifi1010]
platform = atmelsam
board = mkrwifi1010
upload_port = /dev/cu.usbmodem2101
monitor_port = /dev/cu.usbmodem2101
build_src_filter =
    +<satellite-firmware/src/>
build_flags =
    -iquote satellite-firmware/include

lib_deps =
    arduino-libraries/RTCZero
    arduino-libraries/Arduino_BQ24195
    arduino-libraries/Arduino_MKRGPS
    arduino-libraries/WiFiNINA

[env:mega2560]
platform = atmelavr
board = megaatmega2560
upload_port = /dev/cu.usbmodem11201
monitor_port = /dev/cu.usbmodem11201
build_src_filter =
    +<ground-station-firmware/src/>
build_flags =
    -iquote ground-station-firmware/include
