export const systemConfigs = [
  {
    target: 'TELEMETRY',
    title: 'TLM',
    fields: [
      ['ENABLE', 'EN'],
      ['TELEMETRY', 'SELF'],
      ['INTERVAL_S', 'INT'],
    ],
    getOptions: ['ENABLE', 'TELEMETRY', 'INTERVAL_S'],
  },
  {
    target: 'RTC',
    title: 'RTC',
    fields: [
      ['CURRENT_TIME', 'TIME'],
      ['SYNC', 'SYNC'],
      ['SOURCE', 'SRC'],
      ['TELEMETRY', 'TLM'],
    ],
    getOptions: ['CURRENT_TIME', 'SYNC', 'SOURCE', 'TELEMETRY'],
  },
  {
    target: 'LED',
    title: 'LED',
    fields: [
      ['ENABLE', 'EN'],
      ['STATE', 'STATE'],
      ['COLOR', 'CLR'],
      ['TELEMETRY', 'TLM'],
    ],
    getOptions: ['ENABLE', 'STATE', 'COLOR', 'TELEMETRY'],
  },
  {
    target: 'BATTERY',
    title: 'BAT',
    fields: [
      ['AVAILABLE', 'AVL'],
      ['TELEMETRY', 'TLM'],
      ['CHARGE_PERCENT_P', 'PCT'],
      ['VOLTAGE_V', 'BATV'],
      ['CHARGE_VOLTAGE_V', 'CHGV'],
      ['CHARGE_CURRENT_A', 'CHGA'],
    ],
    getOptions: ['AVAILABLE', 'TELEMETRY', 'CHARGE_PERCENT_P', 'VOLTAGE_V', 'CHARGE_VOLTAGE_V', 'CHARGE_CURRENT_A'],
  },
  {
    target: 'GPS',
    title: 'GPS',
    fields: [
      ['ENABLE', 'EN'],
      ['AVAILABLE', 'AVL'],
      ['SATELLITES_N', 'SATS'],
      ['LATITUDE_D', 'LAT'],
      ['LONGITUDE_D', 'LON'],
      ['ALTITUDE_M', 'ALT'],
      ['SPEED_KPH', 'SPD'],
      ['TELEMETRY', 'TLM'],
    ],
    getOptions: ['ENABLE', 'AVAILABLE', 'SATELLITES_N', 'LATITUDE_D', 'LONGITUDE_D', 'ALTITUDE_M', 'SPEED_KPH', 'TELEMETRY'],
  },
  {
    target: 'THERMAL',
    title: 'THM',
    fields: [
      ['ENABLE', 'EN'],
      ['AVAILABLE', 'AVL'],
      ['TEMPERATURE_C', 'TMP'],
      ['HUMIDITY_P', 'RH'],
      ['TELEMETRY', 'TLM'],
    ],
    getOptions: ['ENABLE', 'AVAILABLE', 'TEMPERATURE_C', 'HUMIDITY_P', 'TELEMETRY'],
  },
  {
    target: 'IMU',
    title: 'IMU',
    fields: [
      ['ENABLE', 'EN'],
      ['AVAILABLE', 'AVL'],
      ['TELEMETRY', 'TLM'],
      ['HEADING_DEG', 'HDG'],
      ['X_MS2', 'X'],
      ['Y_MS2', 'Y'],
      ['Z_MS2', 'Z'],
      ['GYRO_X_DPS', 'GX'],
      ['GYRO_Y_DPS', 'GY'],
      ['GYRO_Z_DPS', 'GZ'],
      ['MAG_X_UT', 'MX'],
      ['MAG_Y_UT', 'MY'],
      ['MAG_Z_UT', 'MZ'],
    ],
    getOptions: ['ENABLE', 'AVAILABLE', 'X_MS2', 'Y_MS2', 'Z_MS2', 'GYRO_X_DPS', 'GYRO_Y_DPS', 'GYRO_Z_DPS', 'MAG_X_UT', 'MAG_Y_UT', 'MAG_Z_UT', 'HEADING_DEG', 'TELEMETRY'],
  },
  {
    target: 'ADCS',
    title: 'ADCS',
    fields: [
      ['ENABLE', 'EN'],
      ['AVAILABLE', 'AVL'],
      ['SOURCE', 'SRC'],
      ['TELEMETRY', 'TLM'],
      ['ROLL_DEG', 'ROL'],
      ['PITCH_DEG', 'PIT'],
      ['HEADING_DEG', 'HDG'],
      ['YAW_RATE_DPS', 'YAW'],
    ],
    getOptions: ['ENABLE', 'AVAILABLE', 'SOURCE', 'ROLL_DEG', 'PITCH_DEG', 'HEADING_DEG', 'YAW_RATE_DPS', 'TELEMETRY'],
  },
]
